{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interpose.fullname" . }}-otel-collector
  labels:
    {{- include "interpose.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: prom-exporter
      port: 8889
      targetPort: prom-exporter
  selector:
    {{- include "interpose.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
{{- end }}
