name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: What's missing or awkward today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
      description: If you have one in mind. Not required.
    validations:
      required: false
