"""create audit_entries

Revision ID: 04ef9f18fb8f
Revises: 
Create Date: 2026-07-22 11:49:28.119076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04ef9f18fb8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('server', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('args_hash', sa.Text(), nullable=False),
    sa.Column('args_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policies_fired', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('this_hash', sa.Text(), nullable=False),
    sa.Column('hitl_ticket_id', sa.UUID(), nullable=True),
    sa.Column('hitl_reviewer', sa.Text(), nullable=True),
    sa.Column('hitl_decision', sa.Text(), nullable=True),
    sa.Column('hitl_rationale', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('INTENT', 'COMPLETED', 'DENIED', 'HELD', 'UPSTREAM_ERROR')", name='ck_audit_entries_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['audit_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_agent_time', 'audit_entries', ['agent_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_status_time', 'audit_entries', ['status', 'timestamp'], unique=False)
    op.create_index('idx_audit_trace', 'audit_entries', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_trace', table_name='audit_entries')
    op.drop_index('idx_audit_status_time', table_name='audit_entries')
    op.drop_index('idx_audit_agent_time', table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
