"""add control-plane anomaly, incident, risk-score history tables

Revision ID: 2a594d020568
Revises: d3c3515c3d76
Create Date: 2026-08-05 16:21:51.853069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a594d020568'
down_revision: Union[str, Sequence[str], None] = 'd3c3515c3d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_flags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('anomaly_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_flags_agent_time', 'anomaly_flags', ['agent_id', 'created_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('promotion_rule', sa.Text(), nullable=False),
    sa.Column('related_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('recommended_response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_agent_time', 'incidents', ['agent_id', 'created_at'], unique=False)
    op.create_table('risk_score_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('context_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_score_snapshots_agent_time', 'risk_score_snapshots', ['agent_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_risk_score_snapshots_agent_time', table_name='risk_score_snapshots')
    op.drop_table('risk_score_snapshots')
    op.drop_index('idx_incidents_agent_time', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('idx_anomaly_flags_agent_time', table_name='anomaly_flags')
    op.drop_table('anomaly_flags')
    # ### end Alembic commands ###
