"""add synthetic telemetry and aggregate tables

Revision ID: d3c3515c3d76
Revises: 1f065f6a585d
Create Date: 2026-08-04 09:15:25.695990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3c3515c3d76'
down_revision: Union[str, Sequence[str], None] = '1f065f6a585d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_aml_pack_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ofac_calls', sa.BigInteger(), nullable=False),
    sa.Column('sanctions_matches', sa.BigInteger(), nullable=False),
    sa.Column('transaction_graph_calls', sa.BigInteger(), nullable=False),
    sa.Column('structuring_alerts', sa.BigInteger(), nullable=False),
    sa.Column('mark_investigated_denied', sa.BigInteger(), nullable=False),
    sa.Column('mark_investigated_approved', sa.BigInteger(), nullable=False),
    sa.Column('mark_investigated_auto_passed', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_aml_pack_daily_source_day', 'agg_aml_pack_daily', ['source', 'day'], unique=False)
    op.create_table('agg_cost_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_cost_daily_source_day', 'agg_cost_daily', ['source', 'day'], unique=False)
    op.create_table('agg_hitl_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reviewer_group', sa.Text(), nullable=False),
    sa.Column('tickets_created', sa.BigInteger(), nullable=False),
    sa.Column('approved', sa.BigInteger(), nullable=False),
    sa.Column('denied', sa.BigInteger(), nullable=False),
    sa.Column('timed_out', sa.BigInteger(), nullable=False),
    sa.Column('median_response_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_hitl_daily_source_day', 'agg_hitl_daily', ['source', 'day'], unique=False)
    op.create_table('agg_policy_fires_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('policy_name', sa.Text(), nullable=False),
    sa.Column('effect_type', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('fire_count', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_policy_fires_daily_source_day', 'agg_policy_fires_daily', ['source', 'day'], unique=False)
    op.create_table('agg_telemetry_hourly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('hour', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('server', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('call_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('latency_p50_ms', sa.Float(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('latency_p99_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_telemetry_hourly_source_hour', 'agg_telemetry_hourly', ['source', 'hour'], unique=False)
    op.create_table('audit_entries_synthetic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('server', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('args_hash', sa.Text(), nullable=False),
    sa.Column('args_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policies_fired', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('this_hash', sa.Text(), nullable=True),
    sa.Column('hitl_ticket_id', sa.UUID(), nullable=True),
    sa.Column('hitl_reviewer', sa.Text(), nullable=True),
    sa.Column('hitl_decision', sa.Text(), nullable=True),
    sa.Column('hitl_rationale', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_synthetic_agent_time', 'audit_entries_synthetic', ['agent_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_synthetic_server_tool_time', 'audit_entries_synthetic', ['server', 'tool', 'timestamp'], unique=False)
    op.create_index('idx_audit_synthetic_status_time', 'audit_entries_synthetic', ['status', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_synthetic_status_time', table_name='audit_entries_synthetic')
    op.drop_index('idx_audit_synthetic_server_tool_time', table_name='audit_entries_synthetic')
    op.drop_index('idx_audit_synthetic_agent_time', table_name='audit_entries_synthetic')
    op.drop_table('audit_entries_synthetic')
    op.drop_index('idx_agg_telemetry_hourly_source_hour', table_name='agg_telemetry_hourly')
    op.drop_table('agg_telemetry_hourly')
    op.drop_index('idx_agg_policy_fires_daily_source_day', table_name='agg_policy_fires_daily')
    op.drop_table('agg_policy_fires_daily')
    op.drop_index('idx_agg_hitl_daily_source_day', table_name='agg_hitl_daily')
    op.drop_table('agg_hitl_daily')
    op.drop_index('idx_agg_cost_daily_source_day', table_name='agg_cost_daily')
    op.drop_table('agg_cost_daily')
    op.drop_index('idx_agg_aml_pack_daily_source_day', table_name='agg_aml_pack_daily')
    op.drop_table('agg_aml_pack_daily')
    # ### end Alembic commands ###
