# Module inputs (docs/INTERPOSE_SCOPING.md Section 11.6: "minimal inputs, sane
# defaults for everything"). Every default here matches the doc's own cost estimate
# (~$150-200/month: t3.large nodes, db.t4g.medium RDS, cache.t4g.small Redis) -- the
# defaults ARE the reference deployment, not placeholders.

variable "region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "cluster_name" {
  description = "Base name for every resource this module creates (EKS cluster, RDS instance, etc.)."
  type        = string
  default     = "interpose"
}

variable "environment" {
  description = "Short environment tag (dev/staging/prod) -- part of the naming convention (locals.tf), not a behavior switch."
  type        = string
  default     = "dev"
}

variable "tags" {
  description = "Extra tags merged onto every taggable resource, on top of this module's own standard tags (locals.tf)."
  type        = map(string)
  default     = {}
}

# --- Networking ---

variable "vpc_cidr" {
  description = "CIDR block for the VPC. /16 gives ample room for both public and private subnets across multiple AZs."
  type        = string
  default     = "10.0.0.0/16"
}

variable "availability_zone_count" {
  description = "How many AZs to spread subnets across. EKS requires at least 2; 2 is also the cost-minimal choice (each additional AZ's NAT Gateway is a real monthly cost -- see single_nat_gateway below)."
  type        = number
  default     = 2
  validation {
    condition     = var.availability_zone_count >= 2
    error_message = "EKS requires subnets in at least 2 availability zones."
  }
}

variable "single_nat_gateway" {
  description = "true: one NAT Gateway shared across all private subnets (cheaper, a single point of failure for outbound traffic if that AZ has an issue). false: one NAT Gateway per AZ (real production HA, roughly doubles NAT cost). Defaults to the cheaper option -- this module's own reference deployment is a portfolio/demo target, not a production SLA commitment."
  type        = bool
  default     = true
}

# --- EKS ---

variable "kubernetes_version" {
  description = "EKS control plane version."
  type        = string
  default     = "1.30"
}

variable "node_instance_type" {
  description = "EC2 instance type for the managed node group."
  type        = string
  default     = "t3.large"
}

variable "node_desired_size" {
  description = "Desired worker node count."
  type        = number
  default     = 2
}

variable "node_min_size" {
  description = "Minimum worker node count (cluster autoscaler floor, if enabled later -- not wired up by this module)."
  type        = number
  default     = 1
}

variable "node_max_size" {
  description = "Maximum worker node count."
  type        = number
  default     = 4
}

# --- RDS (Postgres) ---

variable "db_instance_class" {
  description = "RDS instance class for the audit-log Postgres database."
  type        = string
  default     = "db.t4g.medium"
}

variable "db_allocated_storage" {
  description = "RDS allocated storage, in GB."
  type        = number
  default     = 20
}

variable "db_name" {
  description = "Database name Interpose's gateway connects to."
  type        = string
  default     = "interpose"
}

variable "db_username" {
  description = "RDS master username. The master password is generated by Terraform (random_password, rds.tf), never a variable."
  type        = string
  default     = "interpose"
}

# --- ElastiCache (Redis) ---

variable "enable_elasticache" {
  description = "true: provision a real ElastiCache Redis replication group (elasticache.tf). false: skip it entirely -- the reference deploy then expects an in-cluster Redis (the Helm chart's own redis.embedded, same toggle the chart already has for local kind). examples/minimal/ sets this false, matching Section 11.6's own scope-reduction for that example."
  type        = bool
  default     = true
}

variable "redis_node_type" {
  description = "ElastiCache node type, only used when enable_elasticache is true."
  type        = string
  default     = "cache.t4g.small"
}

# --- KMS ---

variable "enable_custom_kms" {
  description = "true: provision dedicated KMS keys for RDS/S3 encryption (kms.tf). false: use each service's own AWS-managed default encryption key instead -- functionally still encrypted at rest, just without a customer-managed key to rotate/audit independently. examples/minimal/ sets this false, matching Section 11.6's own scope-reduction for that example."
  type        = bool
  default     = true
}

# --- S3 audit archive ---

variable "audit_archive_glacier_transition_days" {
  description = "Days after which an archived audit-log object transitions from S3 Standard to Glacier (Section 10.7's warm-to-cold tier)."
  type        = number
  default     = 90
}

# --- IRSA (iam.tf) ---

variable "gateway_namespace" {
  description = "Kubernetes namespace the gateway's ServiceAccount lives in -- must match the Helm release's actual namespace for the IRSA trust policy to resolve."
  type        = string
  default     = "interpose-system"
}

variable "gateway_service_account_name" {
  description = "Name of the gateway's Kubernetes ServiceAccount -- must match `interpose.serviceAccountName` (charts/interpose/templates/_helpers.tpl), which defaults to the Helm release's fullname. Override this if the release isn't named \"interpose\"."
  type        = string
  default     = "interpose-interpose"
}
